spring:
  datasource:
#    url: ${env.DATABASE_LOCAL_URL}
#    username: ${env.DATABASE_LOCAL_USERNAME}
#    password: ${env.DATABASE_LOCAL_PASSWORD}
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Bangkok
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${env.GOOGLE_CLIENT_ID}
            clientSecret: ${env.GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${env.EMAIL_USERNAME}
    password: ${env.EMAIL_PASSWORD}
    port: '587'
  ##########################
  # Kafka
  ##########################
  kafka:
    retry:
      topic:
        attempts: 1
    bootstrap-servers: ${env.PORT}:9092
    consumer:
      group-id: bird-trading-platform
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: all
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      log-container-config: off
app:
  auth:
    secretKey: ${env.JWT_SECRETKEY}
    tokenExpiration: 86400000 # a day
#    86400000
    refreshTokenExpiration: 604800000 # 7 days
  cors:
    allowedOrigins: "http://localhost:3000,https://birdstore2nd.vercel.app,https://www.birdland2nd.store,https://admin.birdland2nd.store/,http://localhost:3001"
    allowedMethods: "*"
    allowedHeaders: "*"
    exposedHeaders: "*"
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - https://birdstore2nd.vercel.app
      - http://localhost:8080/oauth2/redirect
      - https://birdland2nd.store/get-token
      - http://localhost:3030/home
      - https://birdstore2nd.vercel.app/get-token
  aws:
    accessKey: ${env.S3_ACCESS_KEY}
    secretKey: ${env.S3_SECRET_KEY}

  email:
    username: ${env.EMAIL_USERNAME}
    verifyLink: "https://thongtienthienphuot.shop/api/v1/users/verify/"
  paypal:
    mode: sandbox
    id: ${env.PAYPAL_ID}
    secret: ${env.PAYPAL_SECRET}
    successUrl: http://localhost:3000/checkout?status=success
    cancelUrl: http://localhost:3000/checkout